# services:
#   nginx:
#     image: nginx:1-alpine
#     ports:
#       - 8089:80
  
#     volumes:
#       - ./public_html:/var/www/html/
#       - ./default.conf:/etc/nginx/conf.d/default.conf
#     links:
#       - php

#   php:
#     image: php:8.0-fpm
#     expose:
#       - 9000
#     volumes:
#       - ./public_html/:/var/www/html/
#       - ./php.conf:/usr/local/etc/php-fpm.d/custom.conf

services:
  php:
    image: php:7.2-apache
    # stdin_open: true
    # tty: true
    ports:
      - "8089:80"
    volumes:
      - ./public_html/:/var/www/html/
      - ./html.conf:/etc/apache2/conf-enabled/html.conf